version: "3"

services:
  server0:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
  server1:
    build: .
    ports:
      - 5001:5000
    volumes:
      - ./:/app
  server2:
    build: .
    ports:
      - 5002:5000
    volumes:
      - ./:/app